import type { Metadata } from "next";
import { StateProvider } from "./context/state";
import { montserrat } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StateProvider>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </StateProvider>
  );
}
